Add UKPA membership to user profile
PyconUK/ironcage pull request #76
Opened 2017-07-06 17:22 UTC by meatballs

Fixes #71

2017-07-07 06:39 UTC, inglesp requested changes
Hi @meatballs -- looks pretty good.

There's a single failing test, which is because the user returned by `accounts.tests.factories.create_user_with_full_profile` doesn't have the `ukpa_membership` attribute set.  This should be an easy fix.  (Running the tests locally should be a matter of `./manage.py test`, and if it's not, please let me know.)

2017-07-07 06:39 UTC, inglesp commented on accounts/forms.py
> +            'ukpa_membership',
Could you rename this to `is_ukpa_member`?

2017-07-07 06:39 UTC, inglesp commented on accounts/templates/accounts/edit_profile.html
> +                <label class="btn btn-default{% if form.ukpa_membership.value == True %} active{% endif %}">
This should test whether `form.ukpa_membership.value == False`.

2017-07-07 06:39 UTC, inglesp commented on accounts/templates/accounts/profile.html
> +              {{ user.ukpa_membership }}
Currently this shows "True" or "none".  Could you change it to "Yes" or "No"?

2017-07-07 06:39 UTC, inglesp commented on reports/views.py
> +
I'm glad this was (apparently!) self-explanatory.

2017-07-07 11:04 UTC, meatballs commented
I think the test failures are now just the ones already fixed by #77

2017-07-10 08:01 UTC, inglesp requested changes
Sorry, something else that's occurred to me: we only want to offer membership to people who have a ticket for the conference.

We can use `User.get_ticket()` to test whether a user has a ticket (it'll return `None` if they don't), and use this to decide whether display the `is_ukpa_member` field on the `edit_profile.html` form.

We should also use whether a user has a ticket or not to determine what `User.profile_complete()` returns.

2017-07-12 16:01 UTC, inglesp requested changes

2017-07-12 16:01 UTC, inglesp commented on accounts/forms.py
> +            self.fields['is_ukpa_member'].disabled = True
Could you add a comment here?  I don't understand what setting `disabled` is for.

2017-07-12 19:06 UTC, meatballs commented on accounts/forms.py
> +            self.fields['is_ukpa_member'].disabled = True
I read somewhere that it prevents the field being used even if somebody attempts to do so by sending a post request directly to the server.

2017-07-19 10:25 UTC, inglesp approved these changes

2017-07-19 10:32 UTC, merged